### ISSUE TITLE
How to understand the role of the parameters MAX_DELTA_WIDTH and MAX_DELTA_HEIGHT

### ISSUE THREAD

**Issue by Utopiaaaaaaa** [JiahuiYu/generative_inpainting#422] opened 2020-03-30 17:30 UTC
I don't understand the function of these two parameters. Can you tell me the the function of these two parameters(MAX_DELTA_WIDTH and MAX_DELTA_HEIGHT)

**Comment by buchholzmd** [comment] 2020-04-11 17:17
Duplicate of #114 

If you look into the code where config.MAX_DELTA_xxx is used, it is found in inpaint_ops.py module and used for the bbox2mask() function.

https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_ops.py#L120-L149

They are used to get random height and width of the random mask, respectively. But to be more specific they are used to create a wider range of mask dimensions, as described in a comment from the author in issue #114

**Closed as completed** 2020-04-11 20:14 UTC
